version: "3.7"

services:
  db:
    image: postgres:13-alpine
    ports:
      - "9432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - listmonk-data:/var/lib/postgresql/data

  app:
    image: listmonk/listmonk:latest
    ports:
      - "9000:9000"
    networks:
      - listmonk
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.toml:/listmonk/config.toml
    command: ["./listmonk", "--config", "config.toml"]

networks:
  listmonk:

volumes:
  listmonk-data:
